name: stash
description: "The fastest, most frictionless way for a developer to save and retrieve valuable knowledge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  cloud_firestore: ^6.0.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1

flutter:
  assets:
    - assets/icons/stash_icon.png
    - assets/icons/stash_icon_foreground.png
    - assets/icons/stash_icon_monochrome.png
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  
  # Standard icon
  image_path: "assets/icons/stash_icon.png"
  
  # Android Adaptive Icon
  adaptive_icon_background: "#002147"
  adaptive_icon_foreground: "assets/icons/stash_icon_foreground.png"
  
  # Android 13+ Themed Icon
  adaptive_icon_monochrome: "assets/icons/stash_icon_monochrome.png"
  
  # iOS
  remove_alpha_ios: true
